[build]
  publish = "_site"
  command = "npm run build"
[[redirects]]
  force = true
  from = "/admin/config.json"
  status = 200
  to = "https://vasyl-content-model.netlify.app/config.json"
  force = true
  from = "/admin/sveltia-cms.js"
  status = 200
  to = "https://vasyl-content-model.netlify.app/sveltia-cms.js"
